//
//  Workspace.swift
//  BaseTemplateManifests
//
//  Created by 김동준 on 9/7/25
//

import ProjectDescription
import ProjectDescriptionHelpers

let workspace = Workspace(
    name: projectEnvironment.appName,
    projects: [
        "Projects/App"
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
